### ISSUE TITLE
Error in as.character(sys.call(sys.parent())[[1L]]) :    cannot coerce type 'closure' to vector of type 'character'

### ISSUE THREAD

**Issue by nicolaycunha** [wzmli/phyloglmm#9]
Hi there, 

After the last R update, I can't run the ***phyloglmm*** functions once again. Now the error is:

`Error in as.character(sys.call(sys.parent())[[1L]]) : 
  cannot coerce type 'closure' to vector of type 'character'`

When trying to reinstall the package, I get an error and the following message:

`** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘glmmTMB’ 1.1.2.3 is being loaded, but >= 1.1.3 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted`

As far as I know, the last available version of ***glmmTMB*** is 1.1.2.3. 

Hope it is an easy fix just related to compatibility among packages. 

Many thanks!

**Comment by bbolker** [comment]
Hi. I changed to require the *development* version of glmmTMB (which has been submitted to CRAN and will, hopefully, be available from there soon).  Can you try

```
remotes::install_github("glmmTMB/glmmTMB/glmmTMB")
```

?

**Comment by nicolaycunha** [comment]
Many thanks for your fast reply!

Yes, just did it and then could reinstall the ***phyloglmm*** package. However, the error persists when trying to run the models:

`Error in as.character(sys.call(sys.parent())[[1L]]) : 
  cannot coerce type 'closure' to vector of type 'character'`


When debugging it I have:

` debug(phylo_lmm)`
```
Warning messages:
1: In get(results[[i]], packages[[i]]) :
  internal error -3 in R_decompress1
2: In get(results[[i]], packages[[i]]) :
  restarting interrupted promise evaluation
3: In get(results[[i]], packages[[i]]) :
  internal error -3 in R_decompress1
```
` traceback(phylo_lmm)`
```Error in x[[i]] : object of type 'closure' is not subsettable```

**Comment by bbolker** [comment]
Hmm.  Could we please have a reproducible example?  Do the tests in https://github.com/wzmli/phyloglmm/blob/master/pkg/tests/testthat/test-basic.R work for you? (Are you running the models in a clean R session?)

I've just fixed one small bug, so you might try reinstalling just in case it fixes your problem.

**Comment by nicolaycunha** [comment]
I reinstalled it and now I can run any model again! I assume that the small bug you fixed did the job. Many thanks once again!
